repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/cathiele/pre-commit-rust
    rev: v0.1.0
    hooks:
      - id: cargo-fmt
        entry: cargo fmt --all
      - id: cargo-audit
      - id: cargo-check
      - id: cargo-clippy
        entry: cargo clippy --fix --allow-dirty --allow-staged
      - id: cargo-test
